export const questions = [
  // Mathematics
  {
    id: 1,
    category: "Mathematics",
    question: "What is the value of π (pi) rounded to two decimal places?",
    options: ["3.12", "3.14", "3.16", "3.18"],
    correctAnswer: "3.14",
  },
  {
    id: 2,
    category: "Mathematics",
    question: "If a = 3 and b = 4, what is the value of (a² + b²)½?",
    options: ["5", "7", "12", "25"],
    correctAnswer: "5",
  },
  {
    id: 3,
    category: "Mathematics",
    question: "What is the square root of 144?",
    options: ["12", "14", "16", "24"],
    correctAnswer: "12",
  },
  {
    id: 4,
    category: "Mathematics",
    question: "If 3y = 27, what is y?",
    options: ["3", "6", "9", "27"],
    correctAnswer: "9",
  },
  {
    id: 5,
    category: "Mathematics",
    question: "What is 15% of 80?",
    options: ["8", "12", "15", "20"],
    correctAnswer: "12",
  },
  {
    id: 6,
    category: "Mathematics",
    question: "Solve for x: 2x - 7 = 15",
    options: ["4", "8", "11", "22"],
    correctAnswer: "11",
  },
  {
    id: 7,
    category: "Mathematics",
    question: "What is the area of a rectangle with length 12 cm and width 5 cm?",
    options: ["17 cm²", "34 cm²", "60 cm²", "70 cm²"],
    correctAnswer: "60 cm²",
  },
  {
    id: 8,
    category: "Mathematics",
    question: "What is the value of 5! (5 factorial)?",
    options: ["25", "60", "120", "720"],
    correctAnswer: "120",
  },
  {
    id: 9,
    category: "Mathematics",
    question: "What comes next in the sequence: 1, 4, 9, 16, 25, ...?",
    options: ["30", "36", "42", "49"],
    correctAnswer: "36",
  },
  {
    id: 10,
    category: "Mathematics",
    question: "If log₁₀(x) = 2, what is x?",
    options: ["20", "100", "200", "1000"],
    correctAnswer: "100",
  },

  // Science
  {
    id: 11,
    category: "Science",
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: "Au",
  },
  {
    id: 12,
    category: "Science",
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctAnswer: "Mars",
  },
  {
    id: 13,
    category: "Science",
    question: "What is the hardest natural substance on Earth?",
    options: ["Platinum", "Iron", "Diamond", "Titanium"],
    correctAnswer: "Diamond",
  },
  {
    id: 14,
    category: "Science",
    question: "Which of these is NOT a primary color of light?",
    options: ["Red", "Green", "Blue", "Yellow"],
    correctAnswer: "Yellow",
  },
  {
    id: 15,
    category: "Science",
    question: "What is the main component of the Sun?",
    options: ["Oxygen", "Helium", "Hydrogen", "Nitrogen"],
    correctAnswer: "Hydrogen",
  },
  {
    id: 16,
    category: "Science",
    question: "Which of these animals is NOT a mammal?",
    options: ["Dolphin", "Bat", "Penguin", "Kangaroo"],
    correctAnswer: "Penguin",
  },
  {
    id: 17,
    category: "Science",
    question: "What is the smallest unit of matter?",
    options: ["Atom", "Molecule", "Cell", "Electron"],
    correctAnswer: "Atom",
  },
  {
    id: 18,
    category: "Science",
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    correctAnswer: "Carbon Dioxide",
  },
  {
    id: 19,
    category: "Science",
    question: "What is the speed of light in vacuum?",
    options: ["300,000 km/s", "150,000 km/s", "200,000 km/s", "250,000 km/s"],
    correctAnswer: "300,000 km/s",
  },
  {
    id: 20,
    category: "Science",
    question: "Which of these is NOT a state of matter?",
    options: ["Solid", "Liquid", "Gas", "Energy"],
    correctAnswer: "Energy",
  },

  // History
  {
    id: 21,
    category: "History",
    question: "Who was the first President of the United States?",
    options: ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"],
    correctAnswer: "George Washington",
  },
  {
    id: 22,
    category: "History",
    question: "In which year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswer: "1945",
  },
  {
    id: 23,
    category: "History",
    question: "Which ancient civilization built the Machu Picchu?",
    options: ["Aztecs", "Mayans", "Incas", "Egyptians"],
    correctAnswer: "Incas",
  },
  {
    id: 24,
    category: "History",
    question: "Who painted the Mona Lisa?",
    options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"],
    correctAnswer: "Leonardo da Vinci",
  },
  {
    id: 25,
    category: "History",
    question: "Which country was NOT part of the Allied Powers during World War II?",
    options: ["United States", "Soviet Union", "Japan", "United Kingdom"],
    correctAnswer: "Japan",
  },
  {
    id: 26,
    category: "History",
    question: "Who was the first Emperor of China?",
    options: ["Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Mao Zedong"],
    correctAnswer: "Qin Shi Huang",
  },
  {
    id: 27,
    category: "History",
    question: "In which year did Nepal abolish its monarchy?",
    options: ["2006", "2008", "2010", "2012"],
    correctAnswer: "2008",
  },
  {
    id: 28,
    category: "History",
    question: "Who wrote 'The Origin of Species'?",
    options: ["Isaac Newton", "Charles Darwin", "Albert Einstein", "Galileo Galilei"],
    correctAnswer: "Charles Darwin",
  },
  {
    id: 29,
    category: "History",
    question: "Which ancient wonder was located in Alexandria?",
    options: ["Hanging Gardens", "Colossus", "Lighthouse", "Temple of Artemis"],
    correctAnswer: "Lighthouse",
  },
  {
    id: 30,
    category: "History",
    question: "Who was the first woman to win a Nobel Prize?",
    options: ["Mother Teresa", "Marie Curie", "Rosa Parks", "Florence Nightingale"],
    correctAnswer: "Marie Curie",
  },

  // Geography
  {
    id: 31,
    category: "Geography",
    question: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    correctAnswer: "Canberra",
  },
  {
    id: 32,
    category: "Geography",
    question: "Which is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswer: "Pacific Ocean",
  },
  {
    id: 33,
    category: "Geography",
    question: "Which country has the largest population in the world?",
    options: ["India", "China", "United States", "Indonesia"],
    correctAnswer: "India",
  },
  {
    id: 34,
    category: "Geography",
    question: "Which mountain is the tallest in the world?",
    options: ["K2", "Mount Everest", "Kangchenjunga", "Makalu"],
    correctAnswer: "Mount Everest",
  },
  {
    id: 35,
    category: "Geography",
    question: "Which river is the longest in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctAnswer: "Nile",
  },
  {
    id: 36,
    category: "Geography",
    question: "Which of these countries is NOT in Europe?",
    options: ["Portugal", "Greece", "Turkey", "Morocco"],
    correctAnswer: "Morocco",
  },
  {
    id: 37,
    category: "Geography",
    question: "What is the capital of Nepal?",
    options: ["Pokhara", "Kathmandu", "Lalitpur", "Bhaktapur"],
    correctAnswer: "Kathmandu",
  },
  {
    id: 38,
    category: "Geography",
    question: "Which desert is the largest in the world?",
    options: ["Gobi", "Kalahari", "Sahara", "Antarctic"],
    correctAnswer: "Antarctic",
  },
  {
    id: 39,
    category: "Geography",
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["China", "Thailand", "South Korea", "Japan"],
    correctAnswer: "Japan",
  },
  {
    id: 40,
    category: "Geography",
    question: "Which is the smallest continent by land area?",
    options: ["Europe", "Australia", "Antarctica", "South America"],
    correctAnswer: "Australia",
  },

  // Literature
  {
    id: 41,
    category: "Literature",
    question: "Who wrote 'Romeo and Juliet'?",
    options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
    correctAnswer: "William Shakespeare",
  },
  {
    id: 42,
    category: "Literature",
    question: "Which novel begins with the line 'It was the best of times, it was the worst of times'?",
    options: ["Oliver Twist", "Great Expectations", "A Tale of Two Cities", "David Copperfield"],
    correctAnswer: "A Tale of Two Cities",
  },
  {
    id: 43,
    category: "Literature",
    question: "Who wrote 'The Odyssey'?",
    options: ["Socrates", "Plato", "Homer", "Aristotle"],
    correctAnswer: "Homer",
  },
  {
    id: 44,
    category: "Literature",
    question: "Which of these is NOT a work by Jane Austen?",
    options: ["Pride and Prejudice", "Emma", "Wuthering Heights", "Sense and Sensibility"],
    correctAnswer: "Wuthering Heights",
  },
  {
    id: 45,
    category: "Literature",
    question: "Who is the author of 'To Kill a Mockingbird'?",
    options: ["Harper Lee", "J.D. Salinger", "F. Scott Fitzgerald", "Ernest Hemingway"],
    correctAnswer: "Harper Lee",
  },
  {
    id: 46,
    category: "Literature",
    question: "Which famous Nepali poet wrote 'Muna Madan'?",
    options: ["Bhanubhakta Acharya", "Laxmi Prasad Devkota", "Balkrishna Sama", "Madhav Prasad Ghimire"],
    correctAnswer: "Laxmi Prasad Devkota",
  },
  {
    id: 47,
    category: "Literature",
    question: "Who wrote '1984'?",
    options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "H.G. Wells"],
    correctAnswer: "George Orwell",
  },
  {
    id: 48,
    category: "Literature",
    question: "Which character says 'To be or not to be, that is the question'?",
    options: ["Macbeth", "Romeo", "Hamlet", "Othello"],
    correctAnswer: "Hamlet",
  },
  {
    id: 49,
    category: "Literature",
    question: "Who wrote 'The Great Gatsby'?",
    options: ["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "William Faulkner"],
    correctAnswer: "F. Scott Fitzgerald",
  },
  {
    id: 50,
    category: "Literature",
    question: "Which of these is NOT one of the Brontë sisters?",
    options: ["Charlotte", "Emily", "Anne", "Jane"],
    correctAnswer: "Jane",
  },

  // Sports
  {
    id: 51,
    category: "Sports",
    question: "Which country won the FIFA World Cup in 2022?",
    options: ["Brazil", "France", "Argentina", "Germany"],
    correctAnswer: "Argentina",
  },
  {
    id: 52,
    category: "Sports",
    question: "In which sport would you perform a slam dunk?",
    options: ["Volleyball", "Basketball", "Tennis", "Football"],
    correctAnswer: "Basketball",
  },
  {
    id: 53,
    category: "Sports",
    question: "How many players are there in a standard cricket team?",
    options: ["9", "10", "11", "12"],
    correctAnswer: "11",
  },
  {
    id: 54,
    category: "Sports",
    question: "Which country has won the most Olympic gold medals?",
    options: ["Russia", "China", "United States", "Germany"],
    correctAnswer: "United States",
  },
  {
    id: 55,
    category: "Sports",
    question: "In which sport would you use a shuttlecock?",
    options: ["Table Tennis", "Badminton", "Tennis", "Squash"],
    correctAnswer: "Badminton",
  },
  {
    id: 56,
    category: "Sports",
    question: "Which sport is known as the 'king of sports' in Nepal?",
    options: ["Cricket", "Football", "Volleyball", "Kabaddi"],
    correctAnswer: "Football",
  },
  {
    id: 57,
    category: "Sports",
    question: "How many rings are on the Olympic flag?",
    options: ["4", "5", "6", "7"],
    correctAnswer: "5",
  },
  {
    id: 58,
    category: "Sports",
    question: "Which Grand Slam tennis tournament is played on clay courts?",
    options: ["Australian Open", "French Open", "Wimbledon", "US Open"],
    correctAnswer: "French Open",
  },
  {
    id: 59,
    category: "Sports",
    question: "In which year were the first modern Olympic Games held?",
    options: ["1886", "1896", "1900", "1904"],
    correctAnswer: "1896",
  },
  {
    id: 60,
    category: "Sports",
    question: "Which sport uses the terms 'strike' and 'spare'?",
    options: ["Golf", "Bowling", "Baseball", "Hockey"],
    correctAnswer: "Bowling",
  },

  // Technology
  {
    id: 61,
    category: "Technology",
    question: "Who is the co-founder of Microsoft?",
    options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Elon Musk"],
    correctAnswer: "Bill Gates",
  },
  {
    id: 62,
    category: "Technology",
    question: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Central Program Utility",
      "Central Processor Utility",
    ],
    correctAnswer: "Central Processing Unit",
  },
  {
    id: 63,
    category: "Technology",
    question: "Which company developed the iPhone?",
    options: ["Samsung", "Google", "Apple", "Microsoft"],
    correctAnswer: "Apple",
  },
  {
    id: 64,
    category: "Technology",
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Hyper Transfer Markup Language",
      "Hyper Text Modern Links",
    ],
    correctAnswer: "Hyper Text Markup Language",
  },
  {
    id: 65,
    category: "Technology",
    question: "Which of these is NOT a programming language?",
    options: ["Java", "Python", "Oracle", "Ruby"],
    correctAnswer: "Oracle",
  },
  {
    id: 66,
    category: "Technology",
    question: "What year was the first iPhone released?",
    options: ["2005", "2007", "2009", "2010"],
    correctAnswer: "2007",
  },
  {
    id: 67,
    category: "Technology",
    question: "Which social media platform was founded by Mark Zuckerberg?",
    options: ["Twitter", "Instagram", "Facebook", "LinkedIn"],
    correctAnswer: "Facebook",
  },
  {
    id: 68,
    category: "Technology",
    question: "What does Wi-Fi stand for?",
    options: ["Wireless Fidelity", "Wireless Fiber", "Wireless Finding", "Wireless Field"],
    correctAnswer: "Wireless Fidelity",
  },
  {
    id: 69,
    category: "Technology",
    question: "Which company owns Android?",
    options: ["Apple", "Microsoft", "Google", "Samsung"],
    correctAnswer: "Google",
  },
  {
    id: 70,
    category: "Technology",
    question: "What is the name of the first artificial satellite launched into space?",
    options: ["Explorer 1", "Sputnik 1", "Vostok 1", "Apollo 1"],
    correctAnswer: "Sputnik 1",
  },

  // General Knowledge
  {
    id: 71,
    category: "General Knowledge",
    question: "What is the currency of Japan?",
    options: ["Yuan", "Won", "Yen", "Ringgit"],
    correctAnswer: "Yen",
  },
  {
    id: 72,
    category: "General Knowledge",
    question: "Which element has the chemical symbol 'O'?",
    options: ["Gold", "Oxygen", "Osmium", "Oganesson"],
    correctAnswer: "Oxygen",
  },
  {
    id: 73,
    category: "General Knowledge",
    question: "How many sides does a hexagon have?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "6",
  },
  {
    id: 74,
    category: "General Knowledge",
    question: "What is the national flower of Nepal?",
    options: ["Rose", "Lotus", "Rhododendron", "Jasmine"],
    correctAnswer: "Rhododendron",
  },
  {
    id: 75,
    category: "General Knowledge",
    question: "Which of these is NOT a primary color in painting?",
    options: ["Red", "Blue", "Yellow", "Green"],
    correctAnswer: "Green",
  },
  {
    id: 76,
    category: "General Knowledge",
    question: "What is the largest internal organ in the human body?",
    options: ["Heart", "Liver", "Brain", "Lungs"],
    correctAnswer: "Liver",
  },
  {
    id: 77,
    category: "General Knowledge",
    question: "Which planet is closest to the Sun?",
    options: ["Venus", "Earth", "Mars", "Mercury"],
    correctAnswer: "Mercury",
  },
  {
    id: 78,
    category: "General Knowledge",
    question: "What is the main language spoken in Brazil?",
    options: ["Spanish", "Portuguese", "English", "French"],
    correctAnswer: "Portuguese",
  },
  {
    id: 79,
    category: "General Knowledge",
    question: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"],
    correctAnswer: "Michelangelo",
  },
  {
    id: 80,
    category: "General Knowledge",
    question: "What is the largest species of big cat in the world?",
    options: ["Lion", "Tiger", "Jaguar", "Leopard"],
    correctAnswer: "Tiger",
  },

  // Entertainment
  {
    id: 81,
    category: "Entertainment",
    question: "Who played the character of Iron Man in the Marvel Cinematic Universe?",
    options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"],
    correctAnswer: "Robert Downey Jr.",
  },
  {
    id: 82,
    category: "Entertainment",
    question: "Which band performed the song 'Bohemian Rhapsody'?",
    options: ["The Beatles", "Led Zeppelin", "Queen", "Pink Floyd"],
    correctAnswer: "Queen",
  },
  {
    id: 83,
    category: "Entertainment",
    question: "Which movie won the Oscar for Best Picture in 2020?",
    options: ["1917", "Joker", "Parasite", "Once Upon a Time in Hollywood"],
    correctAnswer: "Parasite",
  },
  {
    id: 84,
    category: "Entertainment",
    question: "Who is known as the 'King of Pop'?",
    options: ["Elvis Presley", "Michael Jackson", "Prince", "David Bowie"],
    correctAnswer: "Michael Jackson",
  },
  {
    id: 85,
    category: "Entertainment",
    question: "Which TV series features dragons and is based on books by George R.R. Martin?",
    options: ["The Witcher", "Game of Thrones", "Lord of the Rings", "The Last Kingdom"],
    correctAnswer: "Game of Thrones",
  },
  {
    id: 86,
    category: "Entertainment",
    question: "Which famous Nepali movie won the Special Jury Award at the SAARC Film Festival?",
    options: ["Loot", "Kabaddi", "Pashupati Prasad", "Kalo Pothi"],
    correctAnswer: "Kalo Pothi",
  },
  {
    id: 87,
    category: "Entertainment",
    question: "Who directed the movie 'Inception'?",
    options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Quentin Tarantino"],
    correctAnswer: "Christopher Nolan",
  },
  {
    id: 88,
    category: "Entertainment",
    question: "Which of these is NOT a character in the sitcom 'Friends'?",
    options: ["Ross", "Monica", "Phoebe", "Penny"],
    correctAnswer: "Penny",
  },
  {
    id: 89,
    category: "Entertainment",
    question: "Who wrote the Harry Potter book series?",
    options: ["J.R.R. Tolkien", "J.K. Rowling", "George R.R. Martin", "Stephen King"],
    correctAnswer: "J.K. Rowling",
  },
  {
    id: 90,
    category: "Entertainment",
    question: "Which animated movie features a character named Simba?",
    options: ["Finding Nemo", "Shrek", "The Lion King", "Aladdin"],
    correctAnswer: "The Lion King",
  },

  // Current Affairs
  {
    id: 91,
    category: "Current Affairs",
    question: "Which country hosted the 2023 Cricket World Cup?",
    options: ["England", "Australia", "India", "Pakistan"],
    correctAnswer: "India",
  },
  {
    id: 92,
    category: "Current Affairs",
    question: "Who is the current Secretary-General of the United Nations (as of 2024)?",
    options: ["Ban Ki-moon", "Kofi Annan", "António Guterres", "Boutros Boutros-Ghali"],
    correctAnswer: "António Guterres",
  },
  {
    id: 93,
    category: "Current Affairs",
    question: "Which country became the fourth nation to land on the moon in 2023?",
    options: ["Japan", "Israel", "India", "United Arab Emirates"],
    correctAnswer: "India",
  },
  {
    id: 94,
    category: "Current Affairs",
    question: "Which city will host the 2024 Summer Olympics?",
    options: ["Tokyo", "Los Angeles", "Paris", "Beijing"],
    correctAnswer: "Paris",
  },
  {
    id: 95,
    category: "Current Affairs",
    question: "Who is the current Prime Minister of Nepal (as of 2024)?",
    options: ["K.P. Sharma Oli", "Pushpa Kamal Dahal", "Sher Bahadur Deuba", "Baburam Bhattarai"],
    correctAnswer: "K.P. Sharma Oli",
  },
  {
    id: 96,
    category: "Current Affairs",
    question: "Which cryptocurrency was the first to be created?",
    options: ["Ethereum", "Bitcoin", "Dogecoin", "Litecoin"],
    correctAnswer: "Bitcoin",
  },
  {
    id: 97,
    category: "Current Affairs",
    question: "Which company developed ChatGPT?",
    options: ["Google", "Microsoft", "OpenAI", "Meta"],
    correctAnswer: "OpenAI",
  },
  {
    id: 98,
    category: "Current Affairs",
    question: "Which country has the world's largest economy by GDP (as of 2024)?",
    options: ["China", "Japan", "Germany", "United States"],
    correctAnswer: "United States",
  },
  {
    id: 99,
    category: "Current Affairs",
    question: "Which streaming service produced the series 'Stranger Things'?",
    options: ["Amazon Prime", "Disney+", "Netflix", "HBO Max"],
    correctAnswer: "Netflix",
  },
  {
    id: 100,
    category: "Current Affairs",
    question: "Which social media platform was formerly known as Twitter?",
    options: ["Instagram", "X", "Threads", "Bluesky"],
    correctAnswer: "X",
  },

  // Bonus Questions
  {
    id: 101,
    category: "Bonus",
    question: "If you have 10 apples and you give 3 to your friend, how many do you have left?",
    options: ["3", "7", "10", "13"],
    correctAnswer: "7",
  },
  {
    id: 102,
    category: "Bonus",
    question: "What is the capital of France?",
    options: ["London", "Berlin", "Madrid", "Paris"],
    correctAnswer: "Paris",
  },
  {
    id: 103,
    category: "Bonus",
    question: "Which of these is NOT a continent?",
    options: ["Asia", "Europe", "Africa", "Greenland"],
    correctAnswer: "Greenland",
  },
  {
    id: 104,
    category: "Bonus",
    question: "Who wrote the play 'Hamlet'?",
    options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Leo Tolstoy"],
    correctAnswer: "William Shakespeare",
  },
  {
    id: 105,
    category: "Bonus",
    question: "What is the chemical formula for water?",
    options: ["H2O", "CO2", "NaCl", "O2"],
    correctAnswer: "H2O",
  },
]
